name: xskill
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - cfgrib
  - xarray
  - dask
  - esmpy=7.1.0
  - xesmf
  - jupyterlab
  - matplotlib
  - cartopy
  - cdsapi
  - xskillscore 
  - ipykernel